"""
Shared constants for PSX scrapers.
"""

# PSX Sector code to name mapping (actual PSX DPS codes from market-watch)
PSX_SECTOR_CODES = {
    "0801": "Automobile Assembler",
    "0802": "Automobile Parts & Accessories",
    "0803": "Cable & Electrical Goods",
    "0804": "Cement",
    "0805": "Chemical",
    "0806": "Close - End Mutual Fund",
    "0807": "Commercial Banks",
    "0808": "Engineering",
    "0809": "Fertilizer",
    "0810": "Food & Personal Care Products",
    "0811": "Glass & Ceramics",
    "0812": "Insurance",
    "0813": "Inv. Banks / Inv. Cos. / Securities Cos.",
    "0814": "Jute",
    "0815": "Leasing Companies",
    "0816": "Leather & Tanneries",
    "0817": "Miscellaneous",
    "0818": "Modarabas",
    "0819": "Paper & Board",
    "0820": "Oil & Gas Exploration Companies",
    "0821": "Oil & Gas Marketing Companies",
    "0822": "Pharmaceuticals",
    "0823": "Power Generation & Distribution",
    "0824": "Power Generation & Distribution",
    "0825": "Refinery",
    "0826": "Sugar Allied Industries",
    "0827": "Synthetic & Rayon",
    "0828": "Technology & Communication",
    "0829": "Textile Composite",
    "0830": "Textile Spinning",
    "0831": "Textile Weaving",
    "0832": "Tobacco",
    "0833": "Transport",
    "0834": "Vanaspati & Allied Industries",
    "0835": "Woollen",
    "0836": "Real Estate Investment Trust",
    "0837": "Exchange Traded Funds",
    "0838": "Mutual Funds",
}

# Known company websites for logo fetching via Clearbit
COMPANY_WEBSITES = {
    # Banks
    "HBL": "hbl.com",
    "UBL": "ubldigital.com",
    "MCB": "mcb.com.pk",
    "ABL": "abl.com",
    "MEBL": "meezanbank.com",
    "NBP": "nbp.com.pk",
    "BAFL": "bankalfalah.com",
    "BAHL": "bankalhabib.com",
    "FABL": "faysalbank.com",
    "AKBL": "askaribank.com.pk",
    "SNBL": "soneribank.com",
    "JSBL": "jsbl.com",
    "SILK": "silkbank.com.pk",
    "BIPL": "bifreholdings.com",
    # Cement
    "LUCK": "lucky-cement.com",
    "DGKC": "dgcement.com",
    "MLCF": "mapleleafcement.com",
    "FCCL": "fauji.com.pk",
    "KOHC": "kohatcement.com",
    "CHCC": "charatcement.com",
    "PIOC": "pioneercement.com",
    "ACPL": "attockcement.com",
    "BWCL": "bestway.com.pk",
    # Oil & Gas
    "OGDC": "ogdcl.com",
    "PPL": "ppl.com.pk",
    "POL": "pakoil.com.pk",
    "PSO": "psopk.com",
    "SNGP": "ssgc.com.pk",
    "SSGC": "ssgc.com.pk",
    "MARI": "mari-gas.com.pk",
    "ATRL": "attock.com",
    "APL": "attock.com",
    "NRL": "nfrpk.com",
    "BYCO": "byco.com.pk",
    "HASCOL": "hfreholdings.com",
    # Technology
    "SYS": "systemsltd.com",
    "TRG": "trg.com.pk",
    "AVN": "avanceon.com",
    "NETSOL": "netsoltech.com",
    # Telecom
    "PTC": "ptcl.com.pk",
    # Fertilizer
    "EFERT": "engrofertilizers.com",
    "FFC": "ffreholdings.com",
    "FATIMA": "fatima-group.com",
    "FFBL": "ffbl.com",
    # Power
    "HUBC": "hubpower.com",
    "KEL": "ke.com.pk",
    "KAPCO": "kapco.com.pk",
    "NPL": "nishatpower.com",
    "NCPL": "nishat.net",
    # Automobile
    "INDU": "toyota-indus.com",
    "HCAR": "honda.com.pk",
    "PSMC": "suzukipakistan.com",
    "MTL": "millat.com.pk",
    "GHNL": "gfreholdings.com",
    "AGTL": "agriautos.com",
    # Textile
    "NML": "nishatmills.com",
    "NCL": "nishat.net",
    "GATM": "gfreholdings.com",
    "ILP": "interlooppk.com",
    # Food & Beverages
    "NESTLE": "nestle.pk",
    "UNITY": "unityfoodslimited.com",
    "NATF": "nationalfoods.com",
    "FFL": "frieslandcampina.com.pk",
    "QUICE": "mitchellsfruit.com",
    # Pharma
    "SEARL": "searlecompany.com",
    "GLAXO": "pk.gsk.com",
    "FEROZ": "ffreholdings.com",
    "AGP": "agp.com.pk",
    "HINOON": "hinoonsorganic.com",
    # Real Estate
    "DCL": "dolmen.com.pk",
    # Chemicals
    "ENGRO": "engro.com",
    "ICI": "akzonobel.com",
    "LOTCHEM": "lfreholdings.com",
    # Steel
    "ISL": "ittehadsfreel.com",
    "ASTL": "amarasteel.com",
    "INIL": "internationalindustries.com",
    "MUGHAL": "mughalsteel.com.pk",
    # Insurance
    "EFUG": "efugeneral.com",
    "JSGCL": "jsgroup.com",
    "AICL": "adamjeeinsurance.com",
    # Others
    "COLG": "colgate.com.pk",
    "ULEVER": "unilever.pk",
    "PAEL": "pakelectron.com",
    "WAVES": "waves.com.pk",
    "DAWH": "dawood-group.com",
}
